
package com.microsoft.schemas.exchange.services._2006.messages;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ExchangeWebService", targetNamespace = "http://schemas.microsoft.com/exchange/services/2006/messages", wsdlLocation = "file:/Users/probert/Desktop/Services.wsdl.xml")
public class ExchangeWebService
    extends Service
{

    private final static URL EXCHANGEWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.microsoft.schemas.exchange.services._2006.messages.ExchangeWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.microsoft.schemas.exchange.services._2006.messages.ExchangeWebService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/probert/Desktop/Services.wsdl.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/probert/Desktop/Services.wsdl.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EXCHANGEWEBSERVICE_WSDL_LOCATION = url;
    }

    public ExchangeWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExchangeWebService() {
        super(EXCHANGEWEBSERVICE_WSDL_LOCATION, new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeWebService"));
    }

    /**
     * 
     * @return
     *     returns ExchangeServicePortType
     */
    @WebEndpoint(name = "ExchangeWebPort")
    public ExchangeServicePortType getExchangeWebPort() {
        return super.getPort(new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeWebPort"), ExchangeServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExchangeServicePortType
     */
    @WebEndpoint(name = "ExchangeWebPort")
    public ExchangeServicePortType getExchangeWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/exchange/services/2006/messages", "ExchangeWebPort"), ExchangeServicePortType.class, features);
    }

}
